# cf. https://github.com/Azure/AzureML-Containers
FROM mcr.microsoft.com/azureml/intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04

RUN echo "Hello from custom container!"

# opencv-python dependency
RUN apt-get install -y libgl1-mesa-dev